# Use Python base image
FROM python:3.10-slim

# Prevent Python from writing pyc files & run in unbuffered mode
ENV PYTHONUNBUFFERED=1

# Set app directory
WORKDIR /app

# Copy requirements and install
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy app code
COPY . .

# Streamlit-specific configs
EXPOSE 8501
ENV STREAMLIT_PORT=8501 \
    STREAMLIT_ENABLE_CORS=false \
    STREAMLIT_ENABLE_XSRF_PROTECTION=false \
    STREAMLIT_SERVER_HEADLESS=true

# Run the app
CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]
